openapi: "3.1.0"
security:
  - CookieAuth: []
  - ApiKeyAuth: []
tags:
  - name: users
    description: operations related to users
  - name: products
    description: operations related to products
  - name: carts
    description: operations related to carts
servers:
  - url: http://localhost:3000
    description: Local Server
  - url: http://Patiofy.com
    description: Production Server
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: token
      description: Authentication cookie containing the JWT token
    ApiKeyAuth::
      type: apiKey
      in: header
      name: authorization
      description: Api keys for accessing protected endpoints
info:
  title: Patiofy website Api
  description: API for patiofy website
  contact: 
    name: support team
    url: http://Patiofy.com/contactUs
    email: ajaymaroju@techpixe.com
  termsOfServices: http://Patiofy.com/terms
  licence: 
    name: MIT Licence
    url: http://opensource.org/licenses/MIT
paths:
 /patiofy/auth/user/signup:
   post:
      summary: Registration a new user
      description: |
        This endpoint allows a user to register by providing their first name, last name, username, email, password, and a profile photo. 
        It checks if the username or email already exists and sends a verification email upon successful registration.
      tags: 
        - users
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                  description: The user's first name.
                  example: ajay
                lastname:
                  type: string
                  description: The user's last name.
                  example: Maroju
                username:
                  type: string
                  description: The desired username.
                  example: iam_AajY
                email:
                  type: string
                  format: email
                  description: The user's email address.
                  example: marojuajay111@gmail.com
                phone: 
                  type: string
                  description: the user's phone number
                  example: 9000000000
                password:
                  type: string
                  format: password
                  description: The user's password.
                  example: Ajay@110125cfbv
                profilePhoto:
                  type: string
                  format: binary
                  description: The user's profile photo.
      responses:
        '200':
          description: Verification email sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "verification has been sent to the email, please verify"
        '401':
          description: Username or email already exists.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "username already taken, try another"
        '404':
          description: Profile photo is required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "profile photo is required"
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"
   put:
      summary: Verify user account
      description: |
        This endpoint verifies a user's account by decoding the verification token sent to their email. 
        It checks if the verification time has expired and updates the user's status to "active" upon successful verification.
      tags: 
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                verification:
                  type: string
                  description: The base64 encoded verification token sent to the user's email.
      responses:
        '200':
          description: Account verified successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Account verified successfully"
        '408':
          description: Verification time expired.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Time expired, please register"
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal Server Error"
      